---
- name: Define Node Exporter version
  set_fact:
    node_exporter_version: "1.6.1"

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move Node Exporter binary
  command: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/
  args:
    removes: /tmp/node_exporter*

- name: Create Node Exporter service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: Reload systemd

- name: Run Node Exporter directly
  command: /usr/local/bin/node_exporter
  async: 1
  poll: 0

- name: Start and enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes