- name: Create redis_exporter group
  group:
    name: "{{ redis_exporter_group }}"
    state: present

- name: Create redis_exporter user
  user:
    name: "{{ redis_exporter_user }}"
    group: "{{ redis_exporter_group }}"
    system: yes
    shell: /bin/false
    createhome: no

- name: Download Redis Exporter
  get_url:
    url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/redis_exporter.tar.gz"
    mode: '0644'

- name: Extract Redis Exporter
  unarchive:
    src: "/tmp/redis_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move Redis Exporter binary
  copy:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter"
    dest: "{{ redis_exporter_binary }}"
    owner: "{{ redis_exporter_user }}"
    group: "{{ redis_exporter_group }}"
    mode: '0755'
    remote_src: yes

- name: Create systemd service for Redis Exporter
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    mode: '0644'

- name: Reload systemd and enable Redis Exporter
  systemd:
    name: redis_exporter
    daemon_reload: yes
    enabled: yes
    state: started
  notify: Restart Redis Exporter